<TriviaCategoryScreen>:
    GridLayout:
        rows: 3
        padding: (200,0,200,100)
        spacing: [20,10]
        Label:
            text: 'Ready to go ? Hit Start below.'
            size_hint_x: 1
        Button:
            text: 'Start'
            size_hint: .5,.5
            on_press: root.press_start_button()
        Button:
            text: 'Home'
            size_hint: .5,.5
            on_press: root.go_back_home()